package org.freedesktop.pixman1;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /usr/include/pixman-1/pixman.h:221</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class pixman_f_vector extends Structure {
	/** C type : double[3] */
	public double[] v = new double[3];
	public pixman_f_vector() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("v");
	}
	/** @param v C type : double[3] */
	public pixman_f_vector(double v[]) {
		super();
		if ((v.length != this.v.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.v = v;
	}
	public pixman_f_vector(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends pixman_f_vector implements Structure.ByReference {
		
	};
	public static class ByValue extends pixman_f_vector implements Structure.ByValue {
		
	};
}
