package org.freedesktop.pixman1;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /usr/include/pixman-1/pixman.h:1029</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class pixman_trap extends Structure {
	/** C type : pixman_span_fix_t */
	public pixman_span_fix top;
	/** C type : pixman_span_fix_t */
	public pixman_span_fix bot;
	public pixman_trap() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("top", "bot");
	}
	/**
	 * @param top C type : pixman_span_fix_t<br>
	 * @param bot C type : pixman_span_fix_t
	 */
	public pixman_trap(pixman_span_fix top, pixman_span_fix bot) {
		super();
		this.top = top;
		this.bot = bot;
	}
	public pixman_trap(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends pixman_trap implements Structure.ByReference {
		
	};
	public static class ByValue extends pixman_trap implements Structure.ByValue {
		
	};
}
