package org.freedesktop.pixman1;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /usr/include/pixman-1/pixman.h:616</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class pixman_gradient_stop extends Structure {
	/** C type : pixman_fixed_t */
	public int x;
	/** C type : pixman_color_t */
	public pixman_color color;
	public pixman_gradient_stop() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("x", "color");
	}
	/**
	 * @param x C type : pixman_fixed_t<br>
	 * @param color C type : pixman_color_t
	 */
	public pixman_gradient_stop(int x, pixman_color color) {
		super();
		this.x = x;
		this.color = color;
	}
	public pixman_gradient_stop(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends pixman_gradient_stop implements Structure.ByReference {
		
	};
	public static class ByValue extends pixman_gradient_stop implements Structure.ByValue {
		
	};
}
