package org.freedesktop.pixman1;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /usr/include/pixman-1/pixman.h:139</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class pixman_color extends Structure {
	public short red;
	public short green;
	public short blue;
	public short alpha;
	public pixman_color() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("red", "green", "blue", "alpha");
	}
	public pixman_color(short red, short green, short blue, short alpha) {
		super();
		this.red = red;
		this.green = green;
		this.blue = blue;
		this.alpha = alpha;
	}
	public pixman_color(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends pixman_color implements Structure.ByReference {
		
	};
	public static class ByValue extends pixman_color implements Structure.ByValue {
		
	};
}
