package org.freedesktop.pixman1;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /usr/include/pixman-1/pixman.h:491</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class pixman_region32_data extends Structure {
	public NativeLong size;
	public NativeLong numRects;
	public pixman_region32_data() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("size", "numRects");
	}
	public pixman_region32_data(NativeLong size, NativeLong numRects) {
		super();
		this.size = size;
		this.numRects = numRects;
	}
	public pixman_region32_data(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends pixman_region32_data implements Structure.ByReference {
		
	};
	public static class ByValue extends pixman_region32_data implements Structure.ByValue {
		
	};
}
