package org.freedesktop.pixman1;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * Fixed point matrices<br>
 * <i>native declaration : /usr/include/pixman-1/pixman.h:162</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class pixman_vector extends Structure {
	/** C type : pixman_fixed_t[3] */
	public int[] vector = new int[3];
	public pixman_vector() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("vector");
	}
	/** @param vector C type : pixman_fixed_t[3] */
	public pixman_vector(int vector[]) {
		super();
		if ((vector.length != this.vector.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.vector = vector;
	}
	public pixman_vector(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends pixman_vector implements Structure.ByReference {
		
	};
	public static class ByValue extends pixman_vector implements Structure.ByValue {
		
	};
}
