package org.freedesktop.pixman1;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /usr/include/pixman-1/pixman.h:399</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class pixman_region16 extends Structure {
	/** C type : pixman_box16_t */
	public pixman_box16 extents;
	/** C type : pixman_region16_data_t* */
	public org.freedesktop.pixman1.pixman_region16_data.ByReference data;
	public pixman_region16() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("extents", "data");
	}
	/**
	 * @param extents C type : pixman_box16_t<br>
	 * @param data C type : pixman_region16_data_t*
	 */
	public pixman_region16(pixman_box16 extents, org.freedesktop.pixman1.pixman_region16_data.ByReference data) {
		super();
		this.extents = extents;
		this.data = data;
	}
	public pixman_region16(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends pixman_region16 implements Structure.ByReference {
		
	};
	public static class ByValue extends pixman_region16 implements Structure.ByValue {
		
	};
}
